### ISSUE TITLE
Error while executing script.sh

### ISSUE THREAD

**Issue by omi10859** [CuriousLearner/dotfiles#5]
I got this error msg while installing script.sh 
```Error: homebrew/dupes was deprecated. This tap is now empty as all its formulae were migrated.```

Fix: https://github.com/Linuxbrew/brew/issues/701

**Comment by CuriousLearner** [comment]
Hey @omi10859 

Which comment is the exact fix, and where did you exactly got the error?

**Comment by CuriousLearner** [comment]
I think you can just do:

`brew untap homebrew/dupes`

I see we tap the corresponding package here: https://github.com/CuriousLearner/dotfiles/blob/cf7965a750afd6a2580eec1010e71d4b7e4d81ed/setup/setup_mac.sh#L55

We just need to remove this as all the packages in `homebrew/dupes` were migrated to `homebrew/core`.

Do you want to open a PR for the same? @omi10859

**Comment by CuriousLearner** [comment]
Resolved in https://github.com/CuriousLearner/dotfiles/commit/eefa2d9c92389c0b11b4d1f4be867035681c709e
